spring.application.name=tasks-api-java

# Configuração do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração do Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar os comandos SQL no terminal (excelente para acompanhar o JPA trabalhando)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
